
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_and_publish
  jobs:
  - job: Version
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: echo "##vso[task.setvariable variable=versionVar;isOutput=true]$(curl -s https://raw.githubusercontent.com/vkhorikov/CSharpFunctionalExtensions/master/version.txt | head -1)"
      name: setVersionStep
      displayName: Set version
    - script: echo $(setVersionStep.versionVar)
      displayName: Echo version
    - script: echo "##vso[task.setvariable variable=releaseInfoVar;isOutput=true]$(curl -s https://raw.githubusercontent.com/vkhorikov/CSharpFunctionalExtensions/master/version.txt | tail -n +2)"
      name: setReleaseInfoStep
      displayName: Set release info
    - script: echo $(setReleaseInfoStep.releaseInfoVar)
      displayName: Echo release info
    - script: echo "##vso[task.setvariable variable=currentVersionVar;isOutput=true]$(curl -s https://api.github.com/repos/vkhorikov/CSharpFunctionalExtensions/releases | python -c 'import json,sys;obj=json.load(sys.stdin);print obj[0]["tag_name"] if len(obj) > 0 else ""' | cut -c 2-100)"
      name: setCurrentVersionStep
      displayName: Set current version
    - script: echo $(setCurrentVersionStep.currentVersionVar)
      displayName: Echo current version

  - job: Publish
    dependsOn:
    - Version
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      releaseInfo: $[ dependencies.Version.outputs['setReleaseInfoStep.releaseInfoVar'] ]
    condition: eq(dependencies.Version.outputs['setVersionStep.versionVar'], dependencies.Version.outputs['setCurrentVersionStep.currentVersionVar'])
    steps:
    - download: current
      artifact: NuGetPackage
